### ISSUE TITLE
doesn't work when components are returned as functions

### ISSUE THREAD

**Issue by benhalton** [PEZ/reagent-bidi-accountant-example#1]
Hi really liked your example. 

It works fine for me when I have a component like this

`(defmethod page-contents :foo []
    [:a {:href (bidi/path-for routes :bar)} "link"])`

but not when I have the same but returning a function

`(defmethod page-contents :foo []
    (fn [] 
        [:a {:href (bidi/path-for routes :bar)} "link"]))`

I can see that bidi/accountant are working and the session is updated as expected, but the page fn doesn't 'notice' that the route has changed and the component is not rendered.

Any thoughts on what the difference is?

**Comment by PEZ** [comment]
This is actually ”fixed” (worked around) since a while. I forgot to update this issue. I don't recall exactly, but it had to do with reagent caching something.
